### ISSUE TITLE
is this NNPACK support NEON ?

### ISSUE THREAD

**Issue by victorygogogo** [Maratyszcza/caffe-nnpack#10]
is this NNPACK support NEON ?

**Comment by Maratyszcza** [comment]
Yes, NNPACK always uses NEON on ARM and ARM64 systems.

**Comment by victorygogogo** [comment]
can you tell me the gemm function of neon in nnpack ?

**Comment by Maratyszcza** [comment]
NNPACK does not provide a GEMM function. It provides nnp_fully_connected_output is similar to GEMM, but with a different interface. The NEON microkernel is in https://github.com/Maratyszcza/NNPACK/blob/master/src/neon/blas/sgemm.c

**Comment by victorygogogo** [comment]
yes,but this function is hard to use !
 	void nnp_sgemm_only_4x12__neon(size_t k, size_t update, const float* a, const float* b, float* c, size_t row_stride_c) {
	can you tell me what's the parameters mean about k update ,is this support all size matrix ?thank you.

**Comment by Maratyszcza** [comment]
@victorygogogo This function is not intended to be directly used, it is an internal micro-kernel for `nnp_fully_connected_output` and `nnp_convolution_inference` with impicit GEMM algorithm.
