### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by ldmtwo** [Maratyszcza/caffe-nnpack#2]
Sorry, but can you add a little more documentation for compiling NNPack with Caffe or point me to where it is located? Thanks. 

I've been trying to connect the dots by copying files from NNPack and PThreadPool into ./include and ./lib (created dir).  I made lots of changes to the make file. It seems to have compiled. As soon as my ImageNet data is ready, I'll be testing on that. Is there anything else I should be aware of?

**Comment by Maratyszcza** [comment]
1. Make sure you follow the steps in [NNPACK REAME::Building](https://github.com/Maratyszcza/NNPACK#building), in particular that you clone the repo recursively.
2. Build NNPACK, `export NNPACK_ROOT=$PWD` (in the NNPACK directory)
3. Clone `caffe-nnpack`, install dependencies
4. Execute

`````` bash
cd caffe
mkdir build
cmake .. -DCPU_ONLY=1 -DBUILD_python=0 -DBUILD_docs=0 -DBUILD_SHARED_LIBS=0 -DBLAS="open" -DCMAKE_CXX_FLAGS="-std=gnu++11" -G Ninja
ninja```
``````

**Comment by Maratyszcza** [comment]
Also, note that this repo is somewhat abandoned, further work on Caffe integration goes into [nnpack-pr branch of ajtulloch/caffe](https://github.com/ajtulloch/caffe/tree/nnpack-pr). The build instructions are, however, the same.

**Comment by Maratyszcza** [comment]
@ldmtwo Did it solve your problem?

**Comment by ldmtwo** [comment]
Thanks for following up. Since I got it working by hacking through the make
file before your March 31 post, I haven't needed to try your method, which
looks a LOT easier.

I am curious though. I noticed that PeachPy mentions AVX512. When that
hardware feature is available, will NNPack be able to use it automatically?

**Comment by Maratyszcza** [comment]
PeachPy supports AVX-512, but NNPACK doesn't. However, I'm working on AVX-512 kernels for NNPACK.

**Comment by shihenw** [comment]
Hi, @Maratyszcza ,
Thanks for the instructions above. I cloned nnpack-pr branch of ajtulloch/caffe. (I could not start an issue there so I'm posting here, sorry.) To compile with NNPACK, I added `-DUSE_NNPACK=1` for cmake and add `CXXFLAGS += -std=gnu++11` in Makefile. However when I typed "ninja", the compilation failed at the end when linking nnpack library:

```
/usr/bin/ld: /home/shihenw/Research/NNPACK/lib/libnnpack.a(init.c.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/home/shihenw/Research/NNPACK/lib/libnnpack.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
```

Any suggestion?

**Comment by Maratyszcza** [comment]
@shihenw Make sure you have `-DBUILD_python=0 -DBUILD_SHARED_LIBS=0` as well

**Comment by shihenw** [comment]
@Maratyszcza It compiled, thanks. I thought `-DBUILD_SHARED_LIBS=0` would block opencv so I removed it, but it does not.

**Comment by lolongcovas** [comment]
> Make sure you follow the steps in NNPACK REAME::Building, in particular that you clone the repo recursively.
> Build NNPACK, export NNPACK_ROOT=$PWD (in the NNPACK directory)
> Clone caffe-nnpack, install dependencies
> Execute
> cd caffe
> mkdir build
> cmake .. -DCPU_ONLY=1 -DBUILD_python=0 -DBUILD_docs=0 -DBUILD_SHARED_LIBS=0 -DBLAS="open" -DCMAKE_CXX_FLAGS="-std=gnu++11" -G Ninja
> ninja```

I followed these instructions, but I got the following error:

../src/caffe/layers/nnpack_convolution_layer.cpp:36:1: error: ‘nnp_convolution_kernel_transform_strategy’ does not name a type
 nnp_convolution_kernel_transform_strategy nnp_kts(

anybody knows it?

**Comment by Maratyszcza** [comment]
@lolongcovas The recent updates to NNPACK changed the interface a little bit. A PR would be welcome!

**Comment by lolongcovas** [comment]
hi,

finally I fixed these incompatibilities. I will do a PR.

**Comment by zazd** [comment]
@lolongcovas hi，I also have this problem：error: ‘nnp_convolution_kernel_transform_strategy’ does not name a type， would you tell me how can you fix it？

Thanks

**Comment by rookiepig** [comment]
@lolongcovas  hi, get the same issue with you, how can you fix it ? or have you finished the PR ? 

Thanks

**Comment by Alarnti** [comment]
@lolongcovas same issue unfortunately

**Comment by rookiepig** [comment]
@Alarnti  I have solved this problem by manually modifying serveral lines of code. The problem is the caffe nnpack-pr branch is too old to utilize the new feature of NNPACK
