### ISSUE TITLE
Request for a Train_val prototxt example

### ISSUE THREAD

**Issue by anijain2305** [Maratyszcza/caffe-nnpack#5]
Hi,

I am finally able to get the caffe code compile. However, I am not able to figure out how to instantiate a NNPack layer. In the train_val.prototxt files, a convolution layer can be instantiated using CONVOLUTION but there seems to be no easy name for nnpack. Am I missing something? Let me know how can I use the nnconvolution.

**Comment by Maratyszcza** [comment]
You need to specify: `Engine: NNPACK` inside `conv_params`. Also see details in Maratyszcza/NNPACK#9
