### ISSUE TITLE
how to check NNPACK is enabled ?

### ISSUE THREAD

**Issue by victorygogogo** [Maratyszcza/caffe-nnpack#9]
how to check NNPACK is enabled ? 
who can tell me ?

**Comment by Maratyszcza** [comment]
If you set `engine: NNPACK` for a layer, it will run on NNPACK. You may also add a log statement in www.github.com/Maratyszcza/caffe-nnpack/blob/NNPACK/src/caffe/layers/nnpack_convolution_layer.cpp to know for sure
